query UserCompetitions {
  me {
    id
    Competitions {
      competitionId
      roles
      Competition {
        id
        name
        status
        Metadata {
          wcaId
          startDate
        }
      }
    }
  }
}
