mutation ImportCompetition(
  $wcaId: String!
  $teamId: NumericalID
  $orgUserId: NumericalID
) {
  importCompetition(wcaId: $wcaId, teamId: $teamId, orgUserId: $orgUserId) {
    id
    name
    status
    Metadata {
      id
      wcaId
    }
  }
}
